### ISSUE TITLE
Failed to restart Home Assistant

### ISSUE THREAD

**Issue by dani0l** [icarome/zk_teco#1]
I get this error when I try to reboot after this recent update

The system cannot restart because the configuration is not valid: Platform error lock.zk_teco - cannot import name 'LockDevice' from 'homeassistant.components.lock' (/usr/src/homeassistant/homeassistant/components/lock/__init__.py)

**Comment by icarome** [comment]
I'll check it out and update

**Comment by icarome** [comment]
Just updated. Please test and let me know

**Comment by dani0l** [comment]
Fixed - Thanks!
